; INI 파일
; 생성일시: 2026-03-24 12:30:20
; 파일경로: config.ini

[Application]
EnableLogging=false
; V1 신규: 동작 모드 설정
OperationMode=standalone    ; standalone | luckyboxSolution | carrotAPI


[DB]


[Network]
VPNEnable=false
VPNServer=



[LocalStorage]
AutoExportCSV=true
EnableLocalCache=true
AutoExportDeviceCount=15